services:
  db:
    image: postgres:17
    container_name: finflow-postgres
    environment:
      POSTGRES_USER: finflow
      POSTGRES_PASSWORD: finflow
      POSTGRES_DB: finflow
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: finflow-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: finflow-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/finflow
      SPRING_DATASOURCE_USERNAME: finflow
      SPRING_DATASOURCE_PASSWORD: finflow
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: classpath:db/migration

      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

      APPLICATION_SECURITY_JWT_SECRET_KEY: GuQCXPxC97eoCeh3chn6VClDqoZCPuL3pAb0WPA9ZbsRTm39OVn7hNrEP9HhGY/P
    restart: always

volumes:
  postgres-data:
